### ISSUE TITLE
Bug: #653 - Egg Hatching Automatically contributed by (cawk)

### ISSUE THREAD

**Issue by tr0n0s** [NecronomiconCoding/NecroBot#832] opened 2016-07-27 08:41 UTC
#653 - Egg Hatching Automatically contributed by (cawk)
Isn't working

**Comment by cawk** [comment] 2016-07-27 09:09
Works fine for me what seems to be the error ill see what i can do when im home

**Comment by GamespikeYT** [comment] 2016-07-27 09:50
it just puts an egg in the incubator when you launch it i think

**Comment by AileenLumina** [comment] 2016-07-27 10:19
Eggs only hatch if you set the walking speed to 15kmh or lower.

**Comment by GamespikeYT** [comment] 2016-07-27 10:23
Mine is 10 but it still hatches 1 and then i have to restart the program for it to start a new egg

**Comment by cawk** [comment] 2016-07-27 10:26
Strange are you using the regular incubator the unlimited one?
i will check it out soon

**Comment by GamespikeYT** [comment] 2016-07-27 10:28
I only have the infinite one at the moment

**Comment by reflexx666** [comment] 2016-07-27 10:55
I do not think it is in the precompiled version.

**Comment by patrikwlund** [comment] 2016-07-27 11:07
The merged PR is here: https://github.com/NecronomiconCoding/NecroBot/pull/726

It currently only checks incubators once per farming run. I might add checks in-between pokestops later.

I think the version cawk commited was the old one I wrote, which still had the logging bug. The logging bug should no longer be in the current version.

**Comment by GamespikeYT** [comment] 2016-07-27 11:09
Can you do is together with the transferring and recycling? Those are  running every so often

**Comment by patrikwlund** [comment] 2016-07-27 11:32
Sure, that seems reasonable. I'll look at it later if no one else has already done it by then.

**Comment by AileenLumina** [comment] 2016-07-27 11:34
Yeah, I'd also say that it should be done right before the transferring. We'd also need to investigate/research what the different egg hatch distances mean.

**Comment by GamespikeYT** [comment] 2016-07-27 11:34
Thank man :)

**Comment by lorenzowalz** [comment] 2016-07-27 12:55
I also noticed there aren't any outputs for eggs except for putting them in the incubator - not sure if there were plans to update that (to say what hatched, maybe 10 minute intervals give updates, etc).

**Comment by patrikwlund** [comment] 2016-07-27 14:38
PR for more frequent checks [#907](https://github.com/NecronomiconCoding/NecroBot/pull/907)

**Comment by ShawnHardwick** [comment] 2016-07-27 16:55
Not implemented into 0.1.8 release, but someone please compile the code themselves and test this out. If it works as intended, comment on the PR so that a dev knows it has been tested and can be merged with confidence.

**Comment by cawk** [comment] 2016-07-27 17:01
i have the 0.1.7 version and the only bit different on mine is that i have implemented a level reward claiming and it puts eggs into incubators automatically there isnt logging features so it may look in the console as its not doing anything but it does

**Comment by GamespikeYT** [comment] 2016-07-27 18:08
It's been running for some time now on the latest commits, seems to work just fine now :)

**Comment by tr0n0s** [comment] 2016-07-27 22:02
it's fixed in new release :D

**Closed** 2016-07-31 17:41 UTC
Labels: enhancement
