### ISSUE TITLE
 it seems "UseLuckyEggsMinPokemonAmount": is a cap?

### ISSUE THREAD

**Issue by Marsinator** [NecronomiconCoding/NecroBot#1803] opened 2016-08-01 15:46 UTC
https://images-2.discordapp.net/.eJwVyFEOgyAMANC7cACoDbLibQg2aIKW0LqfZXdf9j7fxz2zu80dZkO3EPZTq8zdq8ksjX0TaZ3LONVXuUIxK_W4-DYNCBlfkdYciQgipfSvlAEBYIEVMWEM_JbOftzNfX_BPiHj.tntzx3_N4zeBjDKmcDgQneBhCVw.png

please see the link.
evolved 30, sent home 9, while it could have evolved 39

**Comment by recon88** [comment] 2016-08-01 15:48
Duplicate of #1783

**Closed by recon88** 2016-08-01 15:48 UTC
