### ISSUE TITLE
[Request] create missing config file before first login

### ISSUE THREAD

**Issue by FreddyLIE** [NecronomiconCoding/NecroBot#721] opened 2016-07-26 23:03 UTC
- After fresh compile the Config files are missing.
- When you start the first time you need to choose the authtype.
- After login the server start to connect and than create the missing config.
- Than you spawn on the default coords and get softbanned

**To configure the bot before the "first start" you need to:**
start, login, close, configure, restart.

So to not get softbanned please create config files **before the Login**.

First start: 
1.) Creating missing config files.
2.) "please choose your authtype..."
3.) ... rest

**Comment by FreddyLIE** [comment] 2016-07-26 23:09
Or...
On the first start, you can choose the AuthType.
After choosing, add "Choose your default coords"

**Comment by ShawnHardwick** [comment] 2016-07-27 14:22
Marking this as a duplicate of #683 and closing it. Very similar requests.

**Closed by ShawnHardwick** 2016-07-27 14:22 UTC
Labels: duplicate
