### ISSUE TITLE
[Request] Options to chose what bot needs to do

### ISSUE THREAD

**Issue by giesti** [NecronomiconCoding/NecroBot#860] opened 2016-07-27 11:34 UTC
I would like to focus on hatching eggs instead of catching pokemon/pokestops with an GPX track.

- Catch pokemon -> yes/no
- Spin pokestop always -> yes/no
  If no --> only spin nearby pokestops, if no more eggs

**Comment by SweetCherry** [comment] 2016-07-27 12:18
+1

The best way to to accomplish this would be to build a seperate *.exe just for setting up the configs. With option descriptions and so.

**Comment by ShawnHardwick** [comment] 2016-07-27 17:06
Duplicate of #803. Closing this entry.

**Closed by ShawnHardwick** 2016-07-27 17:06 UTC
