### ISSUE TITLE
Encounter Problem: Lure Pokemon NotAvailable

### ISSUE THREAD

**Issue by NumberXer0** [NecronomiconCoding/NecroBot#746] opened 2016-07-27 00:23 UTC
Using the latest release, it was supposed to support Pokemon spawned by lures. However, every time the bot reaches a lured Pokestop, the title error appears. Is the feature broken or was it not implemented like stated?

**Comment by FuckItAll** [comment] 2016-07-27 00:25
Same, Gotten 1 or 2 pokemon from lure tho out of 10 i captured normally maybe our character is walking to fast?

**Comment by NumberXer0** [comment] 2016-07-27 00:28
Not sure, I'm using the default speed. I can try lowering it and see if it works.

**Comment by carcerDunnit** [comment] 2016-07-27 02:36
Speed at 25 makes has no effect initial start up is fine after 2~3 lure catches   (ATTENTION) Encounter problem: Lure Pokemon NotAvailable, might be related to the null reference error 

(ERROR) System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.CatchIncensePokemonsTask.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\CatchIncensePokemonsTask.cs:line 49

**Comment by Ilses** [comment] 2016-07-27 03:13
This is not a bug. There is no way to check if a lure is available (as far as I can tell, right now), so we send a request to encounter them anyway. Oftentimes, they are not available (perhaps you already caught the lured pokemon, or a lure hasn't spawned something yet, etc). Hence the message.

**Comment by Ecalite** [comment] 2016-07-27 07:56
I disagree. I strongly believe this is a bug. I'm in an area in japan with every single pokestop lured. So just to make sure I don't get the test wrong, I used 4 different bots, start it at different locations of the general area, right on top of a cluster of lured pokestops. I wait 30 minutes after closing the bot to make sure that the lured pokemons will be there as intended. They each get 1 lured pokemon, and nothing more.

**Comment by Ecalite** [comment] 2016-07-27 07:57
Oh, and I know they're lured because i'm using the desktop pokemon scanner that tells you if a pokestop is lured. Just to be sure.. I also use nox on one of my accounts to verify the data.

I can assure you they're all lured.

**Comment by UntilSunrise** [comment] 2016-07-27 08:17
I developed the lure feature.

If a pokestop is lured, i can always see which pokemon will spawn next time but the spawn rate has an intervall. If the intervall isnt expired you will get a lure pokemon NotAvailable message.
Sadly we cant know how long this intervall is....

**Comment by AileenLumina** [comment] 2016-07-27 10:17
Would it help to add an option "Stay at lured PokeStops" in the config.json so if that option is set to true, the bot stays at the lured pokestop, keeps catching the pokemon that spawn there and continues its normal route when the lure module stops?

**Comment by UntilSunrise** [comment] 2016-07-27 10:19
that would be a possibility but i dont know if you catch more pokemon through this...

**Comment by AileenLumina** [comment] 2016-07-27 10:44
Yeah, I agree. That's why it should better be optional (by adding it as an option in the config.json) so we can test it for a while and see if it is useful.

**Comment by ShawnHardwick** [comment] 2016-07-27 15:01
Added to the FAQ. Closing this.

**Closed by ShawnHardwick** 2016-07-27 15:01 UTC
