### ISSUE TITLE
[Request] Pokemon List exporting to file

### ISSUE THREAD

**Issue by blidrosia** [NecronomiconCoding/NecroBot#865] opened 2016-07-27 11:47 UTC
Bot is excellent. No problem, speedy level. 

We want to see our pokemon stats and values. Can you write to file pokemon list?

**Comment by rbnbrls** [comment] 2016-07-27 12:09
#829

**Comment by ShawnHardwick** [comment] 2016-07-27 17:10
Duplicate of #638. Closing this entry.

**Closed by ShawnHardwick** 2016-07-27 17:10 UTC
Labels: duplicate
