### ISSUE TITLE
[REQUEST] CatchEscape/CatchFlee Messages in LogLevel.Warning (Yellow) and No Pokeballs in LogLevel.Info (Red)

### ISSUE THREAD

**Issue by newb23** [NecronomiconCoding/NecroBot#833] opened 2016-07-27 08:48 UTC
Title

Might make things a little more intuitive to look at. A more, "Hey! I did miss that pokemon!" or "Oh shoot! I need pokeballs!"

Not a major change or anything. :P 

Keep up the good work!

**Comment by newb23** [comment] 2016-07-27 09:11
As you can see by the title changes, I am conflicted as to the colors I would be satisfied with...

Long story short, any of the suggestions would be wonderful. Just a little more heads up on status changes.

Thank you!

**Comment by ShawnHardwick** [comment] 2016-07-27 16:59
Duplicate of #738. I believe the devs want to leave red for terminating errors like exceptions. We already get tons of responses about every single yellow and red response people get. I'm sure we dont want to start receiving messages about this.

**Closed by ShawnHardwick** 2016-07-27 16:59 UTC
