### ISSUE TITLE
[ERROR] BOT CRASH ERROR MESSAGE

### ISSUE THREAD

**Issue by pattythesleeper** [NecronomiconCoding/NecroBot#222] opened 2016-07-23 15:31 UTC
Soo ive just tested a bot and it seemed to work great it went to all pokestops in my area and cathed pokemons.
Then after a short time the bot stops whit this error message:

http://pastebin.com/FPvuhg75
(Sorry the message is in norwegian im sorry for that but i hope u guys understand it)

Heres my user settings:

http://prntscr.com/bwjkos

Ive followed the guide on the bot page:

https://github.com/NecronomiconCoding/Pokemon-Go-Bot

i hoped any one could help me solve this problem aswell if theres anything i can do too get beter user settings let me know :)

**Comment by SergioZgz** [comment] 2016-07-23 15:37
Is a connexion closed exception ... this could be because your network is down at that moment or something similar... maybe that server (pokemon servers are balanced) was down for a while... 

The important part of exception is this inner exception => System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not answer properly after a period of time, or established connection failed because the connected host failed to respond.

**Comment by Antidote78** [comment] 2016-07-23 15:38
You could try that : https://github.com/NecronomiconCoding/Pokemon-Go-Bot/issues/209

**Comment by MichaelGatesDev** [comment] 2016-07-23 15:38
Duplicate of #223 and fixed by acb4e0520cbc0fb1333ec9e13e8713f1624e4e59

**Comment by pattythesleeper** [comment] 2016-07-23 15:43
@Antidote78 i cant seem to find any bin?
http://prntscr.com/bwjtzy
http://prntscr.com/bwju48
Where do i find and remove it?

**Comment by lorenzowalz** [comment] 2016-07-23 16:41
Patty - bin is a folder created when you build the project. Each one has a bin (leading to Debug and ultimately the project files).

**Closed** 2016-07-24 00:37 UTC
