### ISSUE TITLE
(ATTENTION) Encounter problem: Lure Pokemon NotAvailable

### ISSUE THREAD

**Issue by Cazs03** [NecronomiconCoding/NecroBot#735] opened 2016-07-26 23:59 UTC

**Comment by Ilses** [comment] 2016-07-27 07:24
Missed this one -- it's not a bug. See #746.

**Comment by UntilSunrise** [comment] 2016-07-27 08:17
I developed the lure feature.

If a pokestop is lured, i can always see which pokemon will spawn next time but the spawn rate has an intervall. If the intervall isnt expired you will get a lure pokemon NotAvailable message.
Sadly we cant know how long this intervall is....

**Comment by ShawnHardwick** [comment] 2016-07-27 15:00
Added to the FAQ. Closing this.

**Closed by ShawnHardwick** 2016-07-27 15:00 UTC
Labels: help wanted
