### ISSUE TITLE
[BUG] Auto Update Erases Longitude / Latitude

### ISSUE THREAD

**Issue by Evlow** [NecronomiconCoding/NecroBot#1042] opened 2016-07-27 21:24 UTC
If you have auto update turned on, it overwrites the Longitude & Latitude

**Comment by kingchenc** [comment] 2016-07-27 21:28
its not a bug, you will find it in config.json.old
But yea, a auto recover system with own settings would be very good :+1:

**Comment by Evlow** [comment] 2016-07-27 21:32
I found it in config.json.old, but really it should keep settings that could get you soft banned the same.

**Comment by titanbullet12** [comment] 2016-07-27 21:33
Indeed. It should automatically get the old l/t from the config and replace them on the new one.

**Comment by pacinoallstars** [comment] 2016-07-27 21:41
yes otherwise the autopdate has no purpose. It's hard to maintain 50 bots this way ^_^

**Comment by starf** [comment] 2016-07-27 21:58
There are other critique parameters that get overridden, like "KeepMinDuplicatePokemon".
For example if you like to have 2 pokemon of each specie you are out of luck after an automatic update, it will transfer your second one automatically. And to make that worse, it will prioritize by CP instead of IV.

**Comment by titanbullet12** [comment] 2016-07-27 22:01
Some options really need to transfer over.

**Comment by mostlybb** [comment] 2016-07-27 22:35
Oh wow, glad I saw this. Can't believe autoupdate is set to on by default now and it overwrites the config when it updates.

**Comment by windyair** [comment] 2016-07-28 03:14
Once auto update is done, the bot will automatically begin to work, and transfer the pokemons that should not be transferred according to the old configuration, e.g, I want to keey IV>85%, while the default value is 95%.  What worse is that you don't even have a chance to react until you see the print from the console, telling you that your pokemons had already been transferred, which cannot be revert!!! OMG! You have to stop the bot and change the config unhappily, cause lots of your pokemons with good IV have gone forever (above 85% is also good enough maybe, 95% is rare indeed).

**Closed** 2016-07-31 17:41 UTC
