### ISSUE TITLE
Transferring output

### ISSUE THREAD

**Issue by jamesdcampbell** [NecronomiconCoding/NecroBot#271] opened 2016-07-23 20:31 UTC
Hey this is a small bug, but when the bot transfers any Pokemon it shows up twice in the console.

**Comment by Rawrlex** [comment] 2016-07-23 21:18
I can approve this. Sometimes even 3 times.

**Comment by ReddoKiddo** [comment] 2016-07-24 00:51
duplicate of #235, will close this one

**Closed by ReddoKiddo** 2016-07-24 00:51 UTC
