### ISSUE TITLE
GPS noice

### ISSUE THREAD

**Issue by spot88** [NecronomiconCoding/NecroBot#825] opened 2016-07-27 07:53 UTC
Is it possible to implement some kind of GPS noice, so it's simulating an actuall GPS location. Like it is now, it might be to "on point". - Just asking, not sure if it's possible.

**Comment by ShawnHardwick** [comment] 2016-07-27 16:50
Duplicate of #808. Post your randomization ideas there.

**Closed by ShawnHardwick** 2016-07-27 16:50 UTC
