### ISSUE TITLE
Bot stopping

### ISSUE THREAD

**Issue by henriquemaciel** [NecronomiconCoding/NecroBot#1739] opened 2016-08-01 11:51 UTC
The bot is stopping at that time:

[03:31:35] You're outside of your defined radius! Walking to start (10817913.2603116m away) in 5 seconds. Is your Coords.ini file correct?

Currently has a setting that forces restart it?

**Comment by Knulen** [comment] 2016-08-01 11:53
I have the same problem. It looks likes it hangs here. But I can't confirm the question or see how to force to confirm it (I use the release.zip)

**Comment by bulubebek** [comment] 2016-08-01 11:55
its seems caused by sniping mechanism (since 0.4.0)

**Comment by jasio77** [comment] 2016-08-01 11:55
It's probably because of sniping issue. Try not using it until there's a fix for it.

**Comment by Sylencer90** [comment] 2016-08-01 11:57
Yeah turned off sniping and the bot was running 10h+ without any issues this night.

**Comment by Harachteh** [comment] 2016-08-01 13:50
Duplicate 
https://github.com/NecronomiconCoding/NecroBot/issues/1694
https://github.com/NecronomiconCoding/NecroBot/issues/1684
https://github.com/NecronomiconCoding/NecroBot/issues/1675

Not sure if it's already fixed in the actual version.

**Comment by Sylencer90** [comment] 2016-08-01 15:34
@Harachteh It's not fixed, sniping still doesn't work in 0.5.0 (atleast for me, tried online and local server).
Requesting a proper guide in the wiki again for setting up sniping.

**Closed** 2016-08-01 15:54 UTC
