### ISSUE TITLE
Lure pokemon not available

### ISSUE THREAD

**Issue by crixon** [NecronomiconCoding/NecroBot#814] opened 2016-07-27 06:57 UTC
After a short time i've get a encounter problem: Lure pokemon not available ... from then no lure pokemon was catched anymore..

**Comment by Ilses** [comment] 2016-07-27 07:25
Duplicate of #771, #746, #735, and not a bug,

**Comment by crixon** [comment] 2016-07-27 08:16
but why are only the first pokemon catched from lure and after the error shows up only normal pokemon are catched for 2 hours now? :D sorry but i think it's a bug

**Comment by UntilSunrise** [comment] 2016-07-27 08:17
I developed the lure feature.

If a pokestop is lured, i can always see which pokemon will spawn next time but the spawn rate has an intervall. If the intervall isnt expired you will get a lure pokemon NotAvailable message.
Sadly we cant know how long this intervall is....

**Comment by crixon** [comment] 2016-07-27 09:19
ah okey but thx for the info! Hopefully it will work sometimes :) maybe there is a way to find out the rate

**Comment by ShawnHardwick** [comment] 2016-07-27 15:00
Added to the FAQ. Closing this.

**Closed by ShawnHardwick** 2016-07-27 15:00 UTC
