### ISSUE TITLE
[Question] About IV display

### ISSUE THREAD

**Issue by kiz9yup** [NecronomiconCoding/NecroBot#812] opened 2016-07-27 06:38 UTC
Is it possible to get a list or a full list of all your pokemons IV's/Perfection
sorted by highest to lowest cp?

the newest version doesn't display anything, would be nice with a list on the command prompt or a notepad.

**Comment by srwgin** [comment] 2016-07-27 06:44
export to excel is better

**Comment by spot88** [comment] 2016-07-27 07:58
Agreed export to excel.

**Comment by tpauwels** [comment] 2016-07-27 08:48
Yeah, would also love an export to excel feature.

**Comment by rbnbrls** [comment] 2016-07-27 09:37
so #829 ?

**Comment by ShawnHardwick** [comment] 2016-07-27 16:42
There are multiple pull requests that implement this in some fashion but have not been merged for one reason or another. Closing this since it is a duplicate of #638.

**Closed by ShawnHardwick** 2016-07-27 16:42 UTC
