### ISSUE TITLE
Google Refresh Token

### ISSUE THREAD

**Issue by VolviX** [NecronomiconCoding/NecroBot#1174] opened 2016-07-28 09:58 UTC
How can I learn my Google Refresh Token? I deleted bot v6 and it does not working at the moment so I can not get it from there. Help :/

**Comment by mich3lam** [comment] 2016-07-28 09:59
Download another bot and get a refresh token. This is a known issue, and people can't stop opening issues about it. Stop the spam, someone needs to take care of all these after that!

**Comment by myo** [comment] 2016-07-28 10:01
downloading another bot won't work

**Comment by GamberroIbz** [comment] 2016-07-28 10:04
No, downloading a new bot wont work.
The token is only created if u logged in to google account, for that u need to get the key in keyboard, and thats the problem

Agree with the spam but no solutions cuz the only one is to copy the key to new version bot, but if u dont hace the old key cuz u just started today with bot?

**Comment by artganify** [comment] 2016-07-28 10:06
Possible duplicate of #1169.

**Comment by bmsimons** [comment] 2016-07-28 10:44
Just copy the authentication token from an older version's config file. That's what I did as a temp. workaround :)

**Comment by rokuon** [comment] 2016-07-28 12:57
what if there is no Config folder and auth file?

**Closed** 2016-07-31 17:41 UTC
