### ISSUE TITLE
Catch pokemon always with perfect states.

### ISSUE THREAD

**Issue by Syntrace** [NecronomiconCoding/NecroBot#796] opened 2016-07-27 05:27 UTC
I think its not human like to catch all pokemon with a curve ball and perfect throw. (210 exp)
Is it possible to add a bool flag in the configfile to randomize the catch behaviour?

**Comment by KevinBassaDevelopment** [comment] 2016-07-27 08:10
Yes pls :)

**Comment by ShawnHardwick** [comment] 2016-07-27 16:25
Duplicate of #764. Please follow up there, closing this entry.

**Closed by ShawnHardwick** 2016-07-27 16:25 UTC
Labels: enhancement
